first = input()
second = input()
third = input()
fourth = input()
fifth = input()
print(first)
print(f"type of {first}: {type(first)}")
print(second)
print(f"type of {second}: {type(second)}")
print(third)
print(f"type of {third}: {type(third)}")
print(fourth)
print(f"type of {fourth}: {type(fourth)}")
print(fifth)
print(f"type of {fifth}: {type(fifth)}")
